trigger:
- main

pool:
  name: 'Default'  # Use your default agent pool

variables:
  tag: '$(Build.BuildId)'  # Unique tag for the image

jobs:
- job: Build
  displayName: 'Build Java Application'
  pool:
    vmImage: 'ubuntu-latest'  # Correct reference to vmImage
  steps:
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: 'build'
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to Dockerfile
      tags: |
        $(tag)
